Add --flatten option

diff --git a/konfig-merge b/konfig-merge
--- a/konfig-merge
+++ b/konfig-merge
@@ -24,15 +24,20 @@ SELF_CMD="$0"
 usage() {
   cat <<'EOF'
 USAGE:
-  konfig-merge <CONFIG1> [<CONFIG2>..]           : merge multiple kubeconfigs
+  konfig-merge <CONF1> <CONF2> [<CONF3>..]       : merge multiple kubeconfigs
+  konfig-merge -f,--flatten <CONF1> [<CONF2>..]  : merge and flatten kubeconfigs
   konfig-merge -e,--extract <CONTEXT> [<CONFIG>] : extract kubeconfig for given context
 
   konfig-merge -h,--help                         : show this message
 EOF
 }
 
-merge_contexts() {
+merge_raw() {
   KUBECONFIG="$*" $KUBECTL config view --raw --merge
+}
+
+merge_flat() {
+  KUBECONFIG="$*" $KUBECTL config view --flatten --merge
 }
 
 extract_context() {
@@ -65,12 +70,19 @@ main() {
     extract_context "${@:2}"
   elif [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
     usage
+  elif [[ "${1}" == '-f' || "${1}" == '--flatten' ]]; then
+    if [[ "$#" -lt 2 ]]; then
+      echo "error: not enough arguments" >&2
+      usage
+      exit 1
+    fi
+    merge_flat "${@:2}"
   elif [[ "${1}" =~ ^-(.*) ]]; then
     echo "error: unrecognized flag \"${1}\"" >&2
     usage
     exit 1
   elif [[ "$#" -gt 1 ]]; then
-    merge_contexts "${@}"
+    merge_raw "${@}"
   else
     echo "error: not enough arguments" >&2
     usage
